apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: task-service-app
  template:
    metadata:
      labels:
        app: task-service-app
    spec:
      containers:
        - name: task-service
          image: aefimow/task-service:v2
          ports:
            - name: tsksvc-port
              containerPort: 8000
          env:
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: task-service-config
                  key: SERVER_PORT
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: task-service-config
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: task-service-config
                  key: MONGO_PORT
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: task-service-config
                  key: MONGO_DB
            - name: SSL
              valueFrom:
                configMapKeyRef:
                  name: task-service-config
                  key: SSL
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGO_USER
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: MONGO_PASS
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
            initialDelaySeconds: 5
            periodSeconds: 2
